### ISSUE TITLE
node-sass devDependencies missing

### ISSUE THREAD

**Issue by DanielAsher** [hediet/visualization#2]
Hi Henning,

thank you for this incredible work. Your flurry of activity is awe inspiring!

I ran into a issue when I ran `npm run dev` on `simple-demo`:
```bash
ERROR in ./src/style.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/style.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at getDefaultSassImplementation (/sandbox/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/sandbox/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/sandbox/node_modules/sass-loader/dist/index.js:40:61)
 @ ./src/style.scss 2:26-130 43:4-64:5 46:18-122
 @ ./src/index.tsx
 @ multi ./src/index.tsx
```

this was fixed by `npm i node-sass`.

Here is a [repro](https://codesandbox.io/s/hediet-visualization-simple-demo-ognvm) (you may have to restart the server to trigger the build error.)

I forked the sandbox so I could add:
```json
  devServer: {
    disableHostCheck: true
  }
```
into `webpack.config.js` so as to try to avoid the `Invalid Host Error` when running on codesandbox.

best wishes for your glorious future!

**Comment by hediet** [comment]
Thank you very much ❤️ 

[I've setup github actions to build everything to prevent this kind of errors in the future](https://github.com/hediet/visualization/runs/1045539857?check_suite_focus=true).
